### PR TITLE
Python wrapper

### LINKED ISSUE #3: Consider python wrappers for the operations
We might want to consider wrapping the operations exposed via C++ in an easier to use python wrapper.

### LINKED ISSUE #15: Move BigTensor out of the kernels directory
Might want to use it in other places other than the kernels.

### LINKED ISSUE #21: What to do
```python
import tf_big as tfb
x = tfb.big_import([[123]])
y = x+x
```

the above currently fails due to TF type checks:

```
TypeError: Value passed to parameter 'x' has DataType variant not in list of allowed values: bfloat16, float16, float32, float64, uint8, int8, int16, int32, int64, complex64, complex128, string
```

We should decide what to do

### PR DESCRIPTION
**Pull request by mortendahl**
Closes #3 
Closes #15 
Closes #21

### CODE REVIEW

File: tf_big/cc/ops/big_ops.cc [hunk 1]
```diff
@@ -1,32 +1,70 @@
...
     .Input("val1: variant")
-    .Input("val2: variant")
     .Output("res: variant")
-    .SetIsStateful();
+    .SetIsStateful()
+    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
+        ::tensorflow::shape_inference::ShapeHandle val0 = c->input(0);
+        ::tensorflow::shape_inference::ShapeHandle val1 = c->input(1);
+        ::tensorflow::shape_inference::ShapeHandle res;
+        TF_RETURN_IF_ERROR(c->Merge(val0, val1, &res));
```
Comment (justin1121) [inline tf_big/cc/ops/big_ops.cc]: Having trouble understanding what this `Merge` function does. Simple explanation?

Comment (mortendahl) [reply tf_big/cc/ops/big_ops.cc]: It essentially makes sure that the shapes of `val0` and `val1` are the same, filling in missing values from one with concrete values from the other. These filled-in shapes are then stored in `res`. More [details in the TF doc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/shape_inference.h#L230-L251).

Comment (justin1121) [reply tf_big/cc/ops/big_ops.cc]: Thanks!
